"""Pipeline execution engine: local swarm | Snakemake | Nextflow.

Policy: Agent emits validated params (YAML/JSON). Engines own env, scheduling, resume.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any, Literal

from metagenomic_agent.execution.workflow_params import write_workflow_params

EngineName = Literal["langgraph", "snakemake", "nextflow"]


def detect_engine(config: dict[str, Any]) -> EngineName:
    preferred = (config.get("execution", {}) or {}).get("engine", "langgraph")
    if preferred == "nextflow" and shutil.which("nextflow"):
        return "nextflow"
    if preferred == "snakemake" and shutil.which("snakemake"):
        return "snakemake"
    return "langgraph"


def write_nextflow_config(outdir: Path, state: dict[str, Any]) -> Path:
    """Write Nextflow process resources from Agent params (not LLM shell)."""
    outdir.mkdir(parents=True, exist_ok=True)
    # Prefer structured params.yaml produced by workflow_params
    paths = write_workflow_params(state)
    params_yml = Path(paths["params_yaml"])
    cfg = state.get("config", {})
    linux = cfg.get("linux", {})
    threads = int(linux.get("threads") or cfg.get("docker", {}).get("threads") or 8)
    memory = int(linux.get("memory_gb", 32))
    content = f"""
// Auto-generated by Metagenomic Research Agent — resources only
// Task graph & tool params: {params_yml}
params.input = '{state.get("input_path")}'
params.outdir = '{state.get("outdir")}'
params.mode = '{state.get("mode")}'
params.threads = {threads}
params.memory_gb = {memory}
params.params_file = '{params_yml}'
params.kraken2_db = '{cfg.get("paths", {}).get("kraken2_db", "")}'
params.host_index = '{cfg.get("paths", {}).get("host_index", "")}'

process.executor = '{linux.get("nextflow_executor", "local")}'
process.cpus = {threads}
process.memory = '{memory} GB'
"""
    if linux.get("slurm", False):
        content += """
process.executor = 'slurm'
process.queue = '{queue}'
""".format(queue=linux.get("slurm_queue", "normal"))

    path = outdir / "agent.nf.config"
    path.write_text(content.strip() + "\n", encoding="utf-8")
    (outdir / "agent.nf.params.json").write_text(
        json.dumps(
            {
                "input": state.get("input_path"),
                "outdir": state.get("outdir"),
                "query": state.get("user_query"),
                "params_file": str(params_yml),
                "tasks": [{"name": t.get("name"), "agent": t.get("agent")} for t in state.get("tasks", [])],
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    return path


def launch_external(engine: EngineName, state: dict[str, Any], repo_root: Path | None = None) -> dict[str, Any]:
    """Hand off heavy compute to Snakemake/Nextflow using Agent-written params."""
    outdir = Path(state["outdir"])
    param_paths = write_workflow_params(state)
    root = repo_root or Path.cwd()

    if engine == "nextflow":
        nf_dir = root / "workflow" / "nextflow"
        cfg = write_nextflow_config(outdir / "nextflow", state)
        main_nf = nf_dir / "main.nf"
        if not main_nf.exists():
            return {
                "engine": "nextflow",
                "status": "skipped",
                "reason": "main.nf missing",
                "config": str(cfg),
                "params": param_paths,
            }
        cmd = [
            "nextflow",
            "run",
            str(main_nf),
            "-c",
            str(cfg),
            "-params-file",
            param_paths["params_json"],
            "-resume",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        return {
            "engine": "nextflow",
            "status": "success" if proc.returncode == 0 else "failed",
            "returncode": proc.returncode,
            "stdout": proc.stdout[-4000:],
            "stderr": proc.stderr[-4000:],
            "config": str(cfg),
            "params": param_paths,
            "cmd": cmd,
        }
    if engine == "snakemake":
        snakefile = root / "workflow" / "Snakefile"
        smk_cfg = param_paths["snakemake_config"]
        threads = str((state.get("config") or {}).get("linux", {}).get("threads", 4))
        cmd = [
            "snakemake",
            "-j",
            threads,
            "--snakefile",
            str(snakefile),
            "--configfile",
            smk_cfg,
            "--rerun-incomplete",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        return {
            "engine": "snakemake",
            "status": "success" if proc.returncode == 0 else "failed",
            "returncode": proc.returncode,
            "stdout": proc.stdout[-4000:],
            "stderr": proc.stderr[-4000:],
            "params": param_paths,
            "cmd": cmd,
        }
    return {"engine": "langgraph", "status": "inline", "params": param_paths}
