"""Pipeline execution engine: local swarm | Snakemake | Nextflow."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any, Literal

EngineName = Literal["langgraph", "snakemake", "nextflow"]


def detect_engine(config: dict[str, Any]) -> EngineName:
    preferred = (config.get("execution", {}) or {}).get("engine", "langgraph")
    if preferred == "nextflow" and shutil.which("nextflow"):
        return "nextflow"
    if preferred == "snakemake" and shutil.which("snakemake"):
        return "snakemake"
    return "langgraph"


def write_nextflow_config(outdir: Path, state: dict[str, Any]) -> Path:
    """Agent-generated Nextflow config (medium-term roadmap item)."""
    outdir.mkdir(parents=True, exist_ok=True)
    cfg = state.get("config", {})
    linux = cfg.get("linux", {})
    threads = int(linux.get("threads") or cfg.get("docker", {}).get("threads") or 8)
    memory = int(linux.get("memory_gb", 32))
    content = f"""
// Auto-generated by Metagenomic Research Agent
params.input = '{state.get("input_path")}'
params.outdir = '{state.get("outdir")}'
params.mode = '{state.get("mode")}'
params.threads = {threads}
params.memory_gb = {memory}
params.kraken2_db = '{cfg.get("paths", {}).get("kraken2_db", "")}'
params.host_index = '{cfg.get("paths", {}).get("host_index", "")}'

process.executor = '{linux.get("nextflow_executor", "local")}'
process.cpus = {threads}
process.memory = '{memory} GB'
"""
    if linux.get("slurm", False):
        content += """
process.executor = 'slurm'
process.queue = '{queue}'
""".format(queue=linux.get("slurm_queue", "normal"))

    path = outdir / "agent.nf.config"
    path.write_text(content.strip() + "\n", encoding="utf-8")
    (outdir / "agent.nf.params.json").write_text(
        json.dumps(
            {
                "input": state.get("input_path"),
                "outdir": state.get("outdir"),
                "query": state.get("user_query"),
                "tasks": [{"name": t.get("name"), "agent": t.get("agent")} for t in state.get("tasks", [])],
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    return path


def launch_external(engine: EngineName, state: dict[str, Any], repo_root: Path | None = None) -> dict[str, Any]:
    """Optionally hand off heavy compute to Snakemake/Nextflow; Agent remains planner."""
    outdir = Path(state["outdir"])
    if engine == "nextflow":
        nf_dir = (repo_root or Path.cwd()) / "workflow" / "nextflow"
        cfg = write_nextflow_config(outdir / "nextflow", state)
        main_nf = nf_dir / "main.nf"
        if not main_nf.exists():
            return {"engine": "nextflow", "status": "skipped", "reason": "main.nf missing", "config": str(cfg)}
        cmd = ["nextflow", "run", str(main_nf), "-c", str(cfg), "-resume"]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        return {
            "engine": "nextflow",
            "status": "success" if proc.returncode == 0 else "failed",
            "returncode": proc.returncode,
            "stdout": proc.stdout[-4000:],
            "stderr": proc.stderr[-4000:],
            "config": str(cfg),
        }
    if engine == "snakemake":
        snakefile = (repo_root or Path.cwd()) / "workflow" / "Snakefile"
        cmd = [
            "snakemake",
            "-j",
            str(state.get("config", {}).get("linux", {}).get("threads", 4)),
            "--snakefile",
            str(snakefile),
            "--config",
            f"input_dir={state.get('input_path')}",
            f"outdir={state.get('outdir')}",
            f"mode={state.get('mode')}",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        return {
            "engine": "snakemake",
            "status": "success" if proc.returncode == 0 else "failed",
            "returncode": proc.returncode,
            "stdout": proc.stdout[-4000:],
            "stderr": proc.stderr[-4000:],
        }
    return {"engine": "langgraph", "status": "inline"}
