"""HPC batch script generation — SLURM / PBS / SGE (+ Apptainer cache env)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _meta_agent_cmd(state: dict[str, Any]) -> str:
    return (
        f"meta-agent run --input {state.get('input_path')} --outdir {state.get('outdir')} "
        f"--mode {state.get('mode')} --yes "
        f"--query {json.dumps(state.get('user_query') or '')}"
    )


def render_sbatch(
    job_name: str,
    command: str,
    *,
    partition: str = "normal",
    cpus: int = 16,
    mem: str = "64G",
    time: str = "24:00:00",
    account: str | None = None,
    gpus: int = 0,
    outdir: str | None = None,
    sif_dir: str | None = None,
) -> str:
    log = f"{outdir}/logs/slurm-%j.out" if outdir else f"{job_name}-%j.out"
    err = f"{outdir}/logs/slurm-%j.err" if outdir else f"{job_name}-%j.err"
    lines = [
        "#!/bin/bash",
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --partition={partition}",
        f"#SBATCH --cpus-per-task={cpus}",
        f"#SBATCH --mem={mem}",
        f"#SBATCH --time={time}",
        f"#SBATCH --output={log}",
        f"#SBATCH --error={err}",
        "# Generated by Metagenomic Research Agent — resources capped via cluster sense",
    ]
    if account:
        lines.append(f"#SBATCH --account={account}")
    if gpus:
        lines.append(f"#SBATCH --gres=gpu:{gpus}")
    lines.extend(["", "set -euo pipefail", "mkdir -p \"$(dirname \"$0\")\" 2>/dev/null || true"])
    if sif_dir:
        lines.append(f'export APPTAINER_CACHEDIR="{sif_dir}"')
        lines.append(f'export SINGULARITY_CACHEDIR="{sif_dir}"')
        lines.append("# module load apptainer  # uncomment on sites that require it")
    lines.extend(["", command, ""])
    return "\n".join(lines)


def render_pbs(
    job_name: str,
    command: str,
    *,
    queue: str = "workq",
    cpus: int = 16,
    mem: str = "64gb",
    walltime: str = "24:00:00",
    sif_dir: str | None = None,
) -> str:
    lines = [
        "#!/bin/bash",
        f"#PBS -N {job_name}",
        f"#PBS -q {queue}",
        f"#PBS -l select=1:ncpus={cpus}:mem={mem}",
        f"#PBS -l walltime={walltime}",
        f"#PBS -j oe",
        "",
        "set -euo pipefail",
        "cd \"$PBS_O_WORKDIR\"",
    ]
    if sif_dir:
        lines.append(f'export APPTAINER_CACHEDIR="{sif_dir}"')
    lines.extend(["", command, ""])
    return "\n".join(lines)


def render_sge(
    job_name: str,
    command: str,
    *,
    queue: str = "all.q",
    cpus: int = 16,
    mem: str = "64G",
    sif_dir: str | None = None,
) -> str:
    lines = [
        "#!/bin/bash",
        f"#$ -N {job_name}",
        f"#$ -q {queue}",
        f"#$ -pe smp {cpus}",
        f"#$ -l h_vmem={mem}",
        "#$ -cwd",
        "#$ -j y",
        "",
        "set -euo pipefail",
    ]
    if sif_dir:
        lines.append(f'export APPTAINER_CACHEDIR="{sif_dir}"')
    lines.extend(["", command, ""])
    return "\n".join(lines)


def write_scheduler_scripts(outdir: str | Path, state: dict[str, Any], *, allocation: dict[str, Any] | None = None) -> dict[str, str]:
    """Write submit.slurm / submit.pbs / submit.sge using capped allocation."""
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "logs").mkdir(parents=True, exist_ok=True)
    cfg = state.get("config") or {}
    linux = cfg.get("linux") or {}
    appt = cfg.get("apptainer") or {}
    alloc = allocation or {}
    cpus = int(alloc.get("threads") or linux.get("threads") or 16)
    mem_gb = int(alloc.get("memory_gb") or linux.get("memory_gb") or 64)
    gpus = int(alloc.get("gpus") or linux.get("gpus") or 0)
    sif_dir = appt.get("sif_dir") or linux.get("sif_dir") or ""
    cmd = _meta_agent_cmd(state)

    slurm = render_sbatch(
        "meta-agent",
        cmd,
        partition=linux.get("slurm_queue", "normal"),
        cpus=cpus,
        mem=f"{mem_gb}G",
        time=str(linux.get("slurm_time") or "24:00:00"),
        account=linux.get("slurm_account") or None,
        gpus=gpus,
        outdir=str(state.get("outdir") or out),
        sif_dir=sif_dir or None,
    )
    pbs = render_pbs(
        "meta-agent",
        cmd,
        queue=linux.get("pbs_queue") or linux.get("slurm_queue") or "workq",
        cpus=cpus,
        mem=f"{mem_gb}gb",
        walltime=str(linux.get("slurm_time") or "24:00:00"),
        sif_dir=sif_dir or None,
    )
    sge = render_sge(
        "meta-agent",
        cmd,
        queue=linux.get("sge_queue") or "all.q",
        cpus=cpus,
        mem=f"{mem_gb}G",
        sif_dir=sif_dir or None,
    )
    paths = {
        "slurm": str(out / "submit.slurm"),
        "pbs": str(out / "submit.pbs"),
        "sge": str(out / "submit.sge"),
    }
    (out / "submit.slurm").write_text(slurm, encoding="utf-8")
    (out / "submit.pbs").write_text(pbs, encoding="utf-8")
    (out / "submit.sge").write_text(sge, encoding="utf-8")
    for p in paths.values():
        Path(p).chmod(0o755)
    return paths


def write_analysis_sbatch(outdir: str | Path, state: dict[str, Any]) -> Path:
    """Backward-compatible helper."""
    paths = write_scheduler_scripts(outdir, state)
    return Path(paths["slurm"])
