"""Executor / Bioinfo Agent — params, resource patching, HPC/K8s submit specs.

Does not invent free-form shell pipelines. Delegates compute to execute_swarm
and/or Nextflow/Snakemake using Agent-written YAML/JSON params.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from metagenomic_agent.execution.workflow_params import write_workflow_params
from metagenomic_agent.messaging import append_msg, emit


def _hpc_slurm_script(state: dict[str, Any], params: dict[str, str]) -> str:
    cfg = state.get("config") or {}
    linux = cfg.get("linux") or {}
    threads = int(linux.get("threads") or 8)
    mem = int(linux.get("memory_gb") or 32)
    queue = linux.get("slurm_queue") or "normal"
    outdir = state.get("outdir")
    return f"""#!/bin/bash
#SBATCH -J meta-agent
#SBATCH -p {queue}
#SBATCH -c {threads}
#SBATCH --mem={mem}G
#SBATCH -o {outdir}/logs/slurm-%j.out
# Generated by Executor Agent — runs params-driven pipeline (no LLM shell)
set -euo pipefail
meta-agent run --input {state.get('input_path')} --outdir {outdir} --mode {state.get('mode')} \\
  --query {json.dumps(state.get('user_query') or '')} --yes
# Optional engine resume:
# nextflow run workflow/nextflow/main.nf -params-file {params.get('params_json')} -resume
"""


def _k8s_job(state: dict[str, Any], params: dict[str, str]) -> dict[str, Any]:
    cfg = state.get("config") or {}
    linux = cfg.get("linux") or {}
    threads = int(linux.get("threads") or 8)
    mem = int(linux.get("memory_gb") or 32)
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {"name": f"meta-agent-{state.get('run_id') or 'run'}"},
        "spec": {
            "template": {
                "spec": {
                    "restartPolicy": "Never",
                    "containers": [
                        {
                            "name": "meta-agent",
                            "image": (cfg.get("docker") or {}).get("agent_image")
                            or "ghcr.io/bio-apple/metagenomic_agent:latest",
                            "resources": {
                                "requests": {"cpu": str(threads), "memory": f"{mem}Gi"},
                                "limits": {"cpu": str(threads), "memory": f"{mem}Gi"},
                            },
                            "args": [
                                "run",
                                "--input",
                                str(state.get("input_path")),
                                "--outdir",
                                "/out",
                                "--mode",
                                str(state.get("mode") or "docker"),
                                "--yes",
                            ],
                            "env": [
                                {"name": "AGENT_PARAMS", "value": params.get("params_yaml", "")},
                            ],
                        }
                    ],
                }
            }
        },
        "notes": "Apply with kubectl after mounting input/out volumes; Executor emits specs only.",
    }


def prepare_submit_specs(state: dict[str, Any]) -> dict[str, Any]:
    """Write HPC Slurm + Kubernetes Job manifests from validated params."""
    params = write_workflow_params(state)
    out = Path(state["outdir"]) / "executor"
    out.mkdir(parents=True, exist_ok=True)
    slurm = _hpc_slurm_script(state, params)
    (out / "submit.slurm").write_text(slurm, encoding="utf-8")
    k8s = _k8s_job(state, params)
    (out / "job.k8s.yaml").write_text(json.dumps(k8s, indent=2), encoding="utf-8")
    (out / "SUBMIT.md").write_text(
        "# Executor submit guides\n\n"
        f"- Slurm: `sbatch {out / 'submit.slurm'}`\n"
        f"- K8s: adapt volumes then `kubectl apply -f {out / 'job.k8s.yaml'}`\n"
        f"- Params: `{params.get('params_yaml')}`\n"
        "- Policy: adjust resources in params.yaml / config.linux — do not paste LLM shell.\n",
        encoding="utf-8",
    )
    return {
        "slurm": str(out / "submit.slurm"),
        "k8s": str(out / "job.k8s.yaml"),
        "readme": str(out / "SUBMIT.md"),
        "params": params,
    }


def run(state: dict[str, Any], node: dict[str, Any] | None = None) -> dict[str, Any]:
    """Executor entry: emit submit specs then run swarm / external engine."""
    # Lazy import avoids circular: agents → executor_agent → execution.executor → AGENT_REGISTRY
    from metagenomic_agent.execution.executor import execute_swarm

    arts = dict(state.get("artifacts") or {})
    specs = prepare_submit_specs(state)
    arts["executor"] = {
        "role": "executor_bioinfo",
        "slurm": specs["slurm"],
        "k8s": specs["k8s"],
        "params": specs["params"],
        "policy": "params_yaml_then_swarm_or_nf_smk_hpc_k8s_specs",
    }
    amsg = emit("executor", "qc_critic", "status", {"slurm": specs["slurm"]})
    pre = {
        **state,
        "artifacts": arts,
        "messages": state.get("messages", []) + ["Executor wrote HPC/K8s specs under executor/"],
        "agent_messages": append_msg(state.get("agent_messages"), amsg),
    }
    result = execute_swarm(pre)
    result_arts = dict(result.get("artifacts") or {})
    result_arts["executor"] = arts["executor"]
    result["artifacts"] = result_arts
    result["messages"] = list(result.get("messages") or []) + ["Executor finished swarm/engine handoff"]
    return result
