"""Workflow Generator Agent — RAG-backed Nextflow/Snakemake synthesis + reflection hooks."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from metagenomic_agent.knowledge.workflow_rag import retrieve_workflow_snippets
from metagenomic_agent.messaging import append_msg, emit


def _reflect_on_errors(errors: list[dict[str, Any]]) -> list[str]:
    tips = []
    for e in errors:
        msg = str(e.get("error") or "").lower()
        classified = e.get("classified")
        if classified == "oom" or "memory" in msg or "137" in msg:
            tips.append("Reduce threads/memory in Nextflow process directives; prefer MEGAHIT over metaSPAdes.")
        if "not found" in msg or "command not found" in msg:
            tips.append("Pin container images (biocontainers) in nextflow.config for missing binaries.")
        if "db" in msg or "database" in msg:
            tips.append("Export DB paths as params and fail early if unset.")
    return list(dict.fromkeys(tips))


def run(state: dict[str, Any], node: dict[str, Any] | None = None) -> dict[str, Any]:
    query = state.get("user_query") or ""
    engine = ((state.get("config") or {}).get("execution") or {}).get("engine", "nextflow")
    if engine == "langgraph":
        engine_pref = "nextflow"
    else:
        engine_pref = engine

    snippets = retrieve_workflow_snippets(query, engine=engine_pref, top_k=3)
    if not snippets:
        snippets = retrieve_workflow_snippets(query, engine=None, top_k=3)

    dag = state.get("dag") or []
    stages = [f"{n.get('id')}[{n.get('agent')}]" for n in dag]

    nf_lines = [
        "#!/usr/bin/env nextflow",
        f"// Auto-generated by Workflow Agent from RAG snippets + DAG",
        f"// Query: {query[:120]}",
        "params.input = '" + str(state.get("input_path") or "") + "'",
        "params.outdir = '" + str(state.get("outdir") or "results") + "'",
        "params.mode = '" + str(state.get("mode") or "mock") + "'",
        "",
    ]
    for snip in snippets:
        nf_lines.append(f"// RAG: {snip.get('id')} — {snip.get('title')} (score={snip.get('score')})")
        nf_lines.append(snip.get("body") or "")
        nf_lines.append("")

    nf_lines.append("// Agent DAG stages: " + " -> ".join(stages))
    nf_lines.append(
        "\nworkflow {\n  // Prefer meta-agent orchestration unless native rules are fully populated\n"
        "  // AGENT_PIPELINE()\n}\n"
    )

    snake_lines = [
        "# Auto-generated Snakemake (RAG-backed)",
        f"# Query: {query[:120]}",
        'rule all:',
        '    input: "results/final_report.html"',
        "",
        "rule agent_orchestrate:",
        '    output: "results/final_report.html"',
        "    shell:",
        '        "meta-agent run --input {params.input} --outdir results --mode mock --yes"',
        "",
    ]
    for snip in snippets:
        if snip.get("engine") == "snakemake":
            snake_lines.append(f"# RAG: {snip.get('id')}")
            snake_lines.append(snip.get("body") or "")
            snake_lines.append("")

    errors = list((state.get("artifacts") or {}).get("errors") or [])
    reflection = _reflect_on_errors(errors)

    out = Path(state["outdir"]) / "workflow"
    out.mkdir(parents=True, exist_ok=True)
    nf_path = out / "generated.nf"
    sm_path = out / "generated.smk"
    nf_path.write_text("\n".join(nf_lines), encoding="utf-8")
    sm_path.write_text("\n".join(snake_lines), encoding="utf-8")
    meta = {
        "snippets_used": [s.get("id") for s in snippets],
        "nextflow": str(nf_path),
        "snakemake": str(sm_path),
        "reflection": reflection,
    }
    (out / "workflow_generation.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    if reflection:
        (out / "workflow_reflection.md").write_text(
            "# Workflow self-correction notes\n\n" + "\n".join(f"- {t}" for t in reflection) + "\n",
            encoding="utf-8",
        )

    amsg = emit("workflow_agent", "executor", "result", meta)
    return {
        "artifacts": {**state.get("artifacts", {}), "workflow_generation": meta},
        "messages": state.get("messages", [])
        + [f"Workflow Agent wrote {nf_path.name} / {sm_path.name} from {len(snippets)} RAG snippet(s)"],
        "agent_messages": append_msg(state.get("agent_messages"), amsg),
    }
